[package]
name = "web"
version = "0.2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ass = { path = "../ass" }
emu = { path = "../emu" }
rocket = "0.5.0-rc.1"
